pp-min-2.js:1 Error handler not initialized: page is not in an iframe pp-min-2.js:1 Access to XMLHttpRequest at 'https://api.poehali.dev/api/project/badge/displayed?project_name=family-assistant-project' from origin 'https://nasha-semiya.ru' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. _0x1567ac @ pp-min-2.js:1 telemetry-min.js:1 TypeError: Cannot destructure property 'basename' of 'C.useContext(...)' as it is null.     at index-DjtXenAA.js:27:20615     at Ko (index-DjtXenAA.js:7:16875)     at $s (index-DjtXenAA.js:9:1570)     at cu (index-DjtXenAA.js:9:45706)     at Zl (index-DjtXenAA.js:9:39522)     at Yl (index-DjtXenAA.js:9:39450)     at Jl (index-DjtXenAA.js:9:39305)     at Il (index-DjtXenAA.js:9:35701)     at Fl (index-DjtXenAA.js:9:34652)     at x (index-DjtXenAA.js:2:9854) _0x416cf8.<computed>.console.<computed> @ telemetry-min.js:1 Us @ index-DjtXenAA.js:9 Gs.n.callback @ index-DjtXenAA.js:9 bo @ index-DjtXenAA.js:7 $c @ index-DjtXenAA.js:9 Qc @ index-DjtXenAA.js:9 Zc @ index-DjtXenAA.js:9 eu @ index-DjtXenAA.js:9 $l @ index-DjtXenAA.js:9 Fl @ index-DjtXenAA.js:9 x @ index-DjtXenAA.js:2 O @ index-DjtXenAA.js:2 index-DjtXenAA.js:27 Uncaught TypeError: Cannot destructure property 'basename' of 'C.useContext(...)' as it is null.     at index-DjtXenAA.js:27:20615     at Ko (index-DjtXenAA.js:7:16875)     at $s (index-DjtXenAA.js:9:1570)     at cu (index-DjtXenAA.js:9:45706)     at Zl (index-DjtXenAA.js:9:39522)     at Yl (index-DjtXenAA.js:9:39450)     at Jl (index-DjtXenAA.js:9:39305)     at Il (index-DjtXenAA.js:9:35701)     at Fl (index-DjtXenAA.js:9:34652)     at x (index-DjtXenAA.js:2:9854) (anonymous) @ index-DjtXenAA.js:27 Ko @ index-DjtXenAA.js:7 $s @ index-DjtXenAA.js:9 cu @ index-DjtXenAA.js:9 Zl @ index-DjtXenAA.js:9 Yl @ index-DjtXenAA.js:9 Jl @ index-DjtXenAA.js:9 Il @ index-DjtXenAA.js:9 Fl @ index-DjtXenAA.js:9 x @ index-DjtXenAA.js:2 O @ index-DjtXenAA.js:2